#!/usr/bin/env python3
"""
Fetch real market data and build comprehensive market signal outputs.

No synthetic/simulated market data is generated by this script. If live market
sources are unavailable, the run fails unless at least one real symbol was
successfully downloaded.
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import io
import json
import math
import os
import statistics
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests

APP_NAME = "market-signal-analysis"
USER_AGENT = (
    "Mozilla/5.0 (compatible; market-signal-analysis/2.0; "
    "+https://github.com/)"
)
NASDAQ_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
OTHER_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"
YAHOO_CHART_URL = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}"
STOOQ_DAILY_URL = "https://stooq.com/q/d/l/?s={symbol}&i=d"

ANCHOR_TICKERS = [
    "SPY", "QQQ", "IWM", "DIA", "RSP", "VTI", "VEA", "VWO",
    "XLK", "XLF", "XLE", "XLV", "XLY", "XLP", "XLI", "XLB", "XLU", "XLRE", "XLC",
    "TLT", "IEF", "SHY", "HYG", "LQD", "TIP",
    "GLD", "SLV", "USO", "UUP", "FXE", "FXY",
    "BTC-USD", "ETH-USD", "^VIX", "^GSPC", "^IXIC", "^RUT",
]

# Fallback is deliberately broad, but it is only a backup universe. Production
# comprehensive mode pulls live listed symbols from Nasdaq Trader.
FALLBACK_TICKERS = ANCHOR_TICKERS + """
AAPL MSFT NVDA AMZN META GOOGL GOOG AVGO TSLA BRK-B JPM LLY V XOM UNH MA COST
NFLX PG JNJ HD ABBV BAC KO PLTR CRM CVX WMT ORCL CSCO MRK IBM GE AMD LIN MCD
WFC ABT ACN DIS INTU NOW TXN PM ISRG VZ CAT QCOM PEP T AMGN RTX GS BKNG SPGI
UBER LOW PGR HON DHR AXP BSX NEE ETN TJX BLK SYK SCHW C AMAT COP ANET PANW DE
ADBE GILD ADP MMC CB LMT MDLZ SBUX PLD FI UPS MU BMY LRCX KLAC SO BA ICE MO ELV
INTC CME EQIX WM PH ZTS SHW WELL APH MCO CMG CDNS MSI CTAS TDG DUKE NKE SNPS
MCK CL ORLY USB CVS PN CEG EOG AON MMM GD EMR HCA MAR ITW NOC WMB REGN COF AJG
APO CI ROP FTNT TRV AZO BK ECL TFC JCI PYPL CPRT FCX CARR NSC KMI CSX ADSK PCAR
AFL GM OKE SRE PSX URI MNST MET F MPC DLR ALL GWW AMP RCL SPG PSA VLO TEL NXPI
ROST AEP DHI O KR PWR FAST HLT EW KDP TGT FIS LHX MSCI NDAQ PAYX COR LEN BKR
AME KMB EXC OXY HES PRU PEG CCI GEHC VST GLW CTVA PCG IR DAL YUM VRSK DFS TRGP
KVUE OTIS CTSH IDXX XEL EA RMD SYY VMC ED IT ODFL WAB HSY MLM HIG GRMN STZ DD
ROK EFX A IRM EIX LULU DXCM CBRE AVB HPQ MTB WEC XYL ACGL CBOE EBAY FITB TSCO
NUE HWM DOW ANSS BRO LYB WTW RJF CAH WBD MPWR DTE VLTO TROW CHD AWK WST NVR
BIIB STT GPN KEYS HPE HAL EQR FANG DOV PPL SBAC EL BR WDC FE STE TER WY ARE
IFF HBAN PTC EXPE RF ES NTAP CNP WAT APTV MKC ZBH HUBB INVH BALL CINF LUV WBA
PODD LDOS CMS CLX STX COO TDY BAX HOLX MOH TXT DPZ EXR JBL LH SWKS MAS BLDR
ULTA FDS CFG PKG NTRS EG L VSAT IEX J TRMB AKAM K NDSN GEN DG PNR AVY LNT ESS
MAA SNA VTRS ALB KEY TYL ENPH CF EPAM CE INCY BBY IP DOC UDR HST EVRG JBHT
AMCR SWK RL BG TAP JKHY AES WRB NI POOL SOLV CPB REG AIZ KIM CAG ERIE BEN
TECH LKQ UHS IPG MOS APA CRL HII GL ALLE EMN BXP AOS WYNN QRVO FFIV MTCH MKTX
HAS GNRC CZR ETSY FMC PARA MRNA ALGN PAYC DAY HSIC MGM LW
""".split()

SPECIAL_NAME_TOKENS = (
    " warrant", " warrants", " unit", " units", " right", " rights",
    " preferred", " pref ", " depositary", " note due", " debenture",
)


def log(msg: str) -> None:
    print(msg, flush=True)


def normalize_symbol(symbol: str) -> str:
    value = (symbol or "").strip().upper()
    if not value:
        return ""
    # Nasdaq files sometimes use class dots; Yahoo uses dashes.
    value = value.replace(".", "-")
    return value


def dedupe_preserve_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        sym = normalize_symbol(item)
        if not sym or sym in seen:
            continue
        seen.add(sym)
        out.append(sym)
    return out


def request_text(url: str, timeout: int = 30) -> str:
    response = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=timeout)
    response.raise_for_status()
    text = response.text
    if not text or len(text.strip()) < 20:
        raise RuntimeError(f"empty/short response from {url}")
    return text


def parse_nasdaq_pipe_file(text: str, source: str, include_special: bool) -> list[str]:
    # Nasdaq Trader appends a footer line; DictReader will expose it as a row
    # with Symbol/ACT Symbol equal to "File Creation Time". Skip it explicitly.
    reader = csv.DictReader(io.StringIO(text), delimiter="|")
    if not reader.fieldnames:
        raise RuntimeError(f"{source}: missing header")
    fields = set(reader.fieldnames)
    if "Symbol" in fields:
        symbol_field = "Symbol"
    elif "ACT Symbol" in fields:
        symbol_field = "ACT Symbol"
    else:
        raise RuntimeError(f"{source}: unexpected header {reader.fieldnames}")

    symbols: list[str] = []
    for row in reader:
        raw_symbol = (row.get(symbol_field) or "").strip()
        if not raw_symbol or raw_symbol.startswith("File Creation Time"):
            continue
        if (row.get("Test Issue") or "").strip().upper() == "Y":
            continue
        name = (row.get("Security Name") or "").strip().lower()
        if not include_special and any(tok in f" {name} " for tok in SPECIAL_NAME_TOKENS):
            continue
        sym = normalize_symbol(raw_symbol)
        if sym and len(sym) <= 12:
            symbols.append(sym)
    return symbols


def fetch_us_all_universe(include_special: bool = False) -> list[str]:
    symbols: list[str] = []
    for url, source in [(NASDAQ_LISTED_URL, "nasdaqlisted"), (OTHER_LISTED_URL, "otherlisted")]:
        text = request_text(url)
        symbols.extend(parse_nasdaq_pipe_file(text, source, include_special))
    return dedupe_preserve_order(ANCHOR_TICKERS + symbols)


def load_csv_tickers(path: Path) -> list[str]:
    if not path.exists():
        return []
    out: list[str] = []
    with path.open("r", newline="", encoding="utf-8-sig") as f:
        sample = f.read(4096)
        f.seek(0)
        try:
            dialect = csv.Sniffer().sniff(sample) if sample.strip() else csv.excel
        except csv.Error:
            dialect = csv.excel
        reader = csv.DictReader(f, dialect=dialect)
        if reader.fieldnames:
            field_map = {name.lower().strip(): name for name in reader.fieldnames}
            ticker_col = field_map.get("ticker") or field_map.get("symbol") or reader.fieldnames[0]
            for row in reader:
                out.append(row.get(ticker_col, ""))
        else:
            f.seek(0)
            for row in csv.reader(f, dialect=dialect):
                if row:
                    out.append(row[0])
    return dedupe_preserve_order(out)


def resolve_universe(args: argparse.Namespace) -> tuple[list[str], str, str | None]:
    extra = load_csv_tickers(Path(args.tickers_file)) if args.tickers_file else []
    source_note = None
    if args.universe == "custom":
        tickers = extra
        source = f"custom:{args.tickers_file}"
    elif args.universe == "seed":
        tickers = dedupe_preserve_order(FALLBACK_TICKERS + extra)
        source = "built-in broad seed"
    elif args.universe == "anchors":
        tickers = dedupe_preserve_order(ANCHOR_TICKERS + extra)
        source = "cross-asset anchors"
    else:
        try:
            live = fetch_us_all_universe(include_special=args.include_special)
            tickers = dedupe_preserve_order(live + extra)
            source = "Nasdaq Trader listed symbols + anchors"
        except Exception as exc:
            if args.strict_universe:
                raise
            source_note = f"Universe live source failed; used broad built-in fallback. Error: {exc}"
            tickers = dedupe_preserve_order(FALLBACK_TICKERS + extra)
            source = "built-in broad seed fallback"

    if args.max_tickers and args.max_tickers > 0:
        tickers = tickers[: args.max_tickers]
        source_note = (source_note + " " if source_note else "") + f"Universe capped at {args.max_tickers}."
    return tickers, source, source_note


@dataclass
class FetchResult:
    ticker: str
    rows: list[dict[str, Any]]
    source: str | None = None
    error: str | None = None


def fetch_yahoo_chart(symbol: str, period: str, interval: str, timeout: int) -> FetchResult:
    encoded = quote(symbol, safe="")
    url = YAHOO_CHART_URL.format(symbol=encoded)
    params = {
        "range": period,
        "interval": interval,
        "includePrePost": "false",
        "events": "div,splits",
    }
    response = requests.get(url, params=params, headers={"User-Agent": USER_AGENT}, timeout=timeout)
    if response.status_code >= 400:
        snippet = response.text[:180].replace("\n", " ")
        raise RuntimeError(f"Yahoo HTTP {response.status_code}: {snippet}")
    try:
        payload = response.json()
    except Exception as exc:
        snippet = response.text[:240].replace("\n", " ")
        raise RuntimeError(f"Yahoo non-JSON response: {exc}; first chars: {snippet}")

    chart = payload.get("chart") or {}
    error = chart.get("error")
    if error:
        raise RuntimeError(f"Yahoo chart error: {error}")
    results = chart.get("result") or []
    if not results:
        raise RuntimeError("Yahoo chart returned no result")
    result = results[0]
    timestamps = result.get("timestamp") or []
    quote_blocks = ((result.get("indicators") or {}).get("quote") or [])
    if not timestamps or not quote_blocks:
        raise RuntimeError("Yahoo chart returned no timestamp/quote data")
    quote_block = quote_blocks[0]
    adj_block = (((result.get("indicators") or {}).get("adjclose") or [{}])[0])

    opens = quote_block.get("open") or []
    highs = quote_block.get("high") or []
    lows = quote_block.get("low") or []
    closes = quote_block.get("close") or []
    volumes = quote_block.get("volume") or []
    adjcloses = adj_block.get("adjclose") or []

    rows: list[dict[str, Any]] = []
    for i, ts in enumerate(timestamps):
        close = closes[i] if i < len(closes) else None
        if close is None:
            continue
        date = dt.datetime.fromtimestamp(int(ts), tz=dt.timezone.utc).date().isoformat()
        rows.append({
            "date": date,
            "ticker": symbol,
            "open": opens[i] if i < len(opens) else None,
            "high": highs[i] if i < len(highs) else None,
            "low": lows[i] if i < len(lows) else None,
            "close": close,
            "adj_close": adjcloses[i] if i < len(adjcloses) else close,
            "volume": volumes[i] if i < len(volumes) else None,
            "source": "yahoo_chart",
        })
    if not rows:
        raise RuntimeError("Yahoo chart contained no usable close rows")
    return FetchResult(symbol, rows, "yahoo_chart")


def stooq_symbol(symbol: str) -> str:
    value = symbol.lower()
    if value.startswith("^") or "-usd" in value:
        return value
    if "." not in value:
        value = f"{value}.us"
    return value


def fetch_stooq_daily(symbol: str, timeout: int) -> FetchResult:
    url = STOOQ_DAILY_URL.format(symbol=quote(stooq_symbol(symbol), safe=""))
    response = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=timeout)
    if response.status_code >= 400:
        snippet = response.text[:180].replace("\n", " ")
        raise RuntimeError(f"Stooq HTTP {response.status_code}: {snippet}")
    text = response.text
    if "<html" in text[:300].lower():
        raise RuntimeError(f"Stooq returned HTML, first chars: {text[:180].replace(chr(10), ' ')}")
    reader = csv.DictReader(io.StringIO(text))
    expected = {"Date", "Open", "High", "Low", "Close", "Volume"}
    if not reader.fieldnames or not expected.issubset(set(reader.fieldnames)):
        raise RuntimeError(f"Stooq unexpected CSV header: {reader.fieldnames}; first chars: {text[:180].replace(chr(10), ' ')}")
    rows: list[dict[str, Any]] = []
    for row in reader:
        try:
            close = float(row["Close"])
        except Exception:
            continue
        rows.append({
            "date": row["Date"],
            "ticker": symbol,
            "open": to_float(row.get("Open")),
            "high": to_float(row.get("High")),
            "low": to_float(row.get("Low")),
            "close": close,
            "adj_close": close,
            "volume": to_float(row.get("Volume")),
            "source": "stooq_daily",
        })
    if not rows:
        raise RuntimeError("Stooq CSV contained no usable rows")
    return FetchResult(symbol, rows, "stooq_daily")


def to_float(value: Any) -> float | None:
    if value is None or value == "":
        return None
    try:
        v = float(value)
    except Exception:
        return None
    if math.isfinite(v):
        return v
    return None


def fetch_symbol(symbol: str, args: argparse.Namespace) -> FetchResult:
    last_error = None
    for attempt in range(1, args.retries + 2):
        for source in args.sources:
            try:
                if source == "yahoo":
                    return fetch_yahoo_chart(symbol, args.period, args.interval, args.timeout)
                if source == "stooq":
                    return fetch_stooq_daily(symbol, args.timeout)
                raise RuntimeError(f"unknown source {source}")
            except Exception as exc:
                last_error = f"{source}: {exc}"
        if attempt <= args.retries:
            time.sleep(min(2.0 * attempt, 8.0))
    return FetchResult(symbol, [], None, last_error or "unknown fetch error")


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def read_quotes_csv(path: Path) -> list[dict[str, Any]]:
    with path.open("r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def safe_div(a: float, b: float) -> float | None:
    if b == 0 or not math.isfinite(b):
        return None
    return a / b


def mean(values: list[float]) -> float | None:
    vals = [v for v in values if v is not None and math.isfinite(v)]
    return statistics.fmean(vals) if vals else None


def stddev(values: list[float]) -> float | None:
    vals = [v for v in values if v is not None and math.isfinite(v)]
    if len(vals) < 2:
        return None
    return statistics.stdev(vals)


def pct_change(values: list[float], lookback: int) -> float | None:
    if len(values) <= lookback:
        return None
    prev = values[-lookback - 1]
    cur = values[-1]
    if prev is None or cur is None or prev <= 0:
        return None
    return (cur / prev) - 1.0


def simple_rsi(values: list[float], period: int = 14) -> float | None:
    if len(values) <= period:
        return None
    deltas = [values[i] - values[i - 1] for i in range(len(values) - period, len(values))]
    gains = [max(x, 0.0) for x in deltas]
    losses = [abs(min(x, 0.0)) for x in deltas]
    avg_gain = statistics.fmean(gains) if gains else 0.0
    avg_loss = statistics.fmean(losses) if losses else 0.0
    if avg_loss == 0:
        return 100.0 if avg_gain > 0 else 50.0
    rs = avg_gain / avg_loss
    return 100.0 - (100.0 / (1.0 + rs))


def max_drawdown(values: list[float]) -> float | None:
    if not values:
        return None
    peak = values[0]
    worst = 0.0
    for value in values:
        if value is None or value <= 0:
            continue
        peak = max(peak, value)
        dd = (value / peak) - 1.0
        worst = min(worst, dd)
    return worst


def percentile_ranks(rows: list[dict[str, Any]], field: str, out_field: str, reverse: bool = False) -> None:
    valid = [(i, row.get(field)) for i, row in enumerate(rows) if isinstance(row.get(field), (int, float)) and math.isfinite(row[field])]
    if not valid:
        for row in rows:
            row[out_field] = None
        return
    valid.sort(key=lambda x: x[1], reverse=not reverse)
    denom = max(len(valid) - 1, 1)
    for rank, (idx, _value) in enumerate(valid):
        # Higher percentile should mean better. If reverse=True, lower numeric values get better ranks.
        rows[idx][out_field] = round(100.0 * (1.0 - rank / denom), 4)
    for row in rows:
        if out_field not in row:
            row[out_field] = None


def compute_latest_signals(quotes: list[dict[str, Any]], min_history_days: int) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in quotes:
        ticker = row.get("ticker")
        if ticker:
            grouped[ticker].append(row)

    latest_rows: list[dict[str, Any]] = []
    for ticker, rows in grouped.items():
        rows.sort(key=lambda r: r.get("date") or "")
        closes: list[float] = []
        volumes: list[float] = []
        for row in rows:
            close = to_float(row.get("adj_close")) or to_float(row.get("close"))
            if close is not None and close > 0:
                closes.append(close)
                vol = to_float(row.get("volume"))
                volumes.append(vol if vol is not None else 0.0)
        if len(closes) < min_history_days:
            continue

        daily_returns: list[float] = []
        for i in range(1, len(closes)):
            if closes[i - 1] > 0:
                daily_returns.append((closes[i] / closes[i - 1]) - 1.0)
        last = closes[-1]
        sma20 = mean(closes[-20:]) if len(closes) >= 20 else None
        sma50 = mean(closes[-50:]) if len(closes) >= 50 else None
        sma200 = mean(closes[-200:]) if len(closes) >= 200 else None
        high_20 = max(closes[-20:]) if len(closes) >= 20 else None
        low_20 = min(closes[-20:]) if len(closes) >= 20 else None
        high_252 = max(closes[-252:]) if len(closes) >= 252 else max(closes)
        low_252 = min(closes[-252:]) if len(closes) >= 252 else min(closes)
        vol20 = stddev(daily_returns[-20:])
        vol20_ann = vol20 * math.sqrt(252.0) if vol20 is not None else None
        latest_source = rows[-1].get("source") or "unknown"

        out = {
            "ticker": ticker,
            "last_date": rows[-1].get("date"),
            "last_close": round(last, 6),
            "rows": len(closes),
            "source": latest_source,
            "ret_1d": pct_change(closes, 1),
            "ret_5d": pct_change(closes, 5),
            "ret_20d": pct_change(closes, 20),
            "ret_63d": pct_change(closes, 63),
            "ret_126d": pct_change(closes, 126),
            "ret_252d": pct_change(closes, 252),
            "sma20": sma20,
            "sma50": sma50,
            "sma200": sma200,
            "above_sma20": int(sma20 is not None and last > sma20),
            "above_sma50": int(sma50 is not None and last > sma50),
            "above_sma200": int(sma200 is not None and last > sma200),
            "distance_sma50": safe_div(last - sma50, sma50) if sma50 is not None else None,
            "distance_sma200": safe_div(last - sma200, sma200) if sma200 is not None else None,
            "realized_vol_20d": vol20_ann,
            "rsi14": simple_rsi(closes, 14),
            "drawdown_252d": max_drawdown(closes[-252:]),
            "near_20d_high": int(high_20 is not None and last >= high_20 * 0.995),
            "near_20d_low": int(low_20 is not None and last <= low_20 * 1.005),
            "distance_52w_high": safe_div(last - high_252, high_252) if high_252 else None,
            "distance_52w_low": safe_div(last - low_252, low_252) if low_252 else None,
            "avg_volume_20d": mean(volumes[-20:]) if len(volumes) >= 20 else None,
        }
        latest_rows.append(out)

    # Cross-sectional scores. Higher return is better; lower vol/drawdown is better.
    percentile_ranks(latest_rows, "ret_5d", "rank_ret_5d")
    percentile_ranks(latest_rows, "ret_20d", "rank_ret_20d")
    percentile_ranks(latest_rows, "ret_63d", "rank_ret_63d")
    percentile_ranks(latest_rows, "ret_126d", "rank_ret_126d")
    percentile_ranks(latest_rows, "realized_vol_20d", "rank_low_vol_20d", reverse=True)
    percentile_ranks(latest_rows, "drawdown_252d", "rank_drawdown_252d")

    for row in latest_rows:
        components = [
            row.get("rank_ret_5d"),
            row.get("rank_ret_20d"),
            row.get("rank_ret_63d"),
            row.get("rank_ret_126d"),
            row.get("rank_low_vol_20d"),
            row.get("rank_drawdown_252d"),
        ]
        score = mean([float(x) for x in components if x is not None])
        trend_bonus = 0.0
        trend_bonus += 4.0 if row.get("above_sma50") else -4.0
        trend_bonus += 6.0 if row.get("above_sma200") else -6.0
        final_score = max(0.0, min(100.0, (score if score is not None else 50.0) + trend_bonus))
        row["market_signal_score"] = round(final_score, 4)
        if final_score >= 75:
            label = "strong"
        elif final_score >= 55:
            label = "constructive"
        elif final_score >= 45:
            label = "neutral"
        elif final_score >= 25:
            label = "weak"
        else:
            label = "stressed"
        row["signal_label"] = label

    numeric_fields = [
        "ret_1d", "ret_5d", "ret_20d", "ret_63d", "ret_126d", "ret_252d",
        "sma20", "sma50", "sma200", "distance_sma50", "distance_sma200",
        "realized_vol_20d", "rsi14", "drawdown_252d", "distance_52w_high", "distance_52w_low",
        "avg_volume_20d",
    ]
    for row in latest_rows:
        for field in numeric_fields:
            if isinstance(row.get(field), float):
                row[field] = round(row[field], 8)
    latest_rows.sort(key=lambda r: (r.get("market_signal_score") or 0.0), reverse=True)
    return latest_rows


def ratio(count: int, total: int) -> float | None:
    return round(count / total, 6) if total else None


def build_summary(signals: list[dict[str, Any]], manifest: dict[str, Any]) -> dict[str, Any]:
    total = len(signals)
    def count_true(field: str) -> int:
        return sum(1 for row in signals if row.get(field) == 1)
    rets_1d = [row.get("ret_1d") for row in signals if isinstance(row.get("ret_1d"), (int, float))]
    rets_20d = [row.get("ret_20d") for row in signals if isinstance(row.get("ret_20d"), (int, float))]
    scores = [row.get("market_signal_score") for row in signals if isinstance(row.get("market_signal_score"), (int, float))]
    latest_date = max((row.get("last_date") or "" for row in signals), default=None)
    anchors = [row for row in signals if row["ticker"] in ANCHOR_TICKERS]
    summary = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "latest_market_date": latest_date,
        "universe_source": manifest.get("universe_source"),
        "requested_tickers": manifest.get("requested_tickers"),
        "successful_tickers": manifest.get("successful_tickers"),
        "failed_tickers": manifest.get("failed_tickers"),
        "signals_count": total,
        "breadth": {
            "pct_above_sma20": ratio(count_true("above_sma20"), total),
            "pct_above_sma50": ratio(count_true("above_sma50"), total),
            "pct_above_sma200": ratio(count_true("above_sma200"), total),
            "pct_near_20d_high": ratio(count_true("near_20d_high"), total),
            "pct_near_20d_low": ratio(count_true("near_20d_low"), total),
            "pct_positive_1d": ratio(sum(1 for r in rets_1d if r > 0), len(rets_1d)),
            "pct_positive_20d": ratio(sum(1 for r in rets_20d if r > 0), len(rets_20d)),
            "median_ret_20d": round(statistics.median(rets_20d), 8) if rets_20d else None,
            "median_signal_score": round(statistics.median(scores), 4) if scores else None,
        },
        "top_signals": signals[:25],
        "bottom_signals": list(reversed(signals[-25:])),
        "anchors": sorted(anchors, key=lambda r: ANCHOR_TICKERS.index(r["ticker"])),
    }
    return summary


def escape_html(value: Any) -> str:
    text = "" if value is None else str(value)
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def fmt_pct(value: Any) -> str:
    if isinstance(value, (int, float)) and math.isfinite(value):
        return f"{100.0 * value:.2f}%"
    return ""


def write_html_report(path: Path, summary: dict[str, Any]) -> None:
    """Write a static, dependency-free dashboard from real fetched rows."""
    path.parent.mkdir(parents=True, exist_ok=True)
    breadth = summary.get("breadth") or {}

    def rows_table(rows: list[dict[str, Any]], title: str) -> str:
        cols = ["ticker", "signal_label", "market_signal_score", "last_close", "ret_5d", "ret_20d", "ret_63d", "above_sma50", "above_sma200", "realized_vol_20d", "rsi14"]
        body = []
        for row in rows:
            cells = []
            for col in cols:
                value = row.get(col)
                if col.startswith("ret_") or col == "realized_vol_20d":
                    value = fmt_pct(value)
                elif isinstance(value, float):
                    value = f"{value:.4f}"
                cells.append(f"<td>{escape_html(value)}</td>")
            body.append("<tr>" + "".join(cells) + "</tr>")
        header = "".join(f"<th>{escape_html(c)}</th>" for c in cols)
        return f"<section><h2>{escape_html(title)}</h2><div class='table-wrap'><table><thead><tr>{header}</tr></thead><tbody>{''.join(body)}</tbody></table></div></section>"

    def pct_width(value: Any) -> tuple[float, str]:
        if isinstance(value, (int, float)) and math.isfinite(value):
            pct = max(0.0, min(100.0, 100.0 * float(value)))
            return pct, f"{pct:.2f}%"
        return 0.0, ""

    def breadth_chart() -> str:
        items = [
            ("Above SMA20", breadth.get("pct_above_sma20")),
            ("Above SMA50", breadth.get("pct_above_sma50")),
            ("Above SMA200", breadth.get("pct_above_sma200")),
            ("20d positive", breadth.get("pct_positive_20d")),
            ("Near 20d high", breadth.get("pct_near_20d_high")),
            ("Near 20d low", breadth.get("pct_near_20d_low")),
        ]
        bars = []
        for label, raw in items:
            width, text = pct_width(raw)
            bars.append("<div class='bar-row'>" +
                        f"<div class='bar-label'>{escape_html(label)}</div>" +
                        f"<div class='bar-track'><div class='bar-fill' style='width:{width:.2f}%'></div></div>" +
                        f"<div class='bar-value'>{escape_html(text)}</div>" +
                        "</div>")
        return "<section><h2>Market breadth</h2><div class='chart-card'>" + "".join(bars) + "</div></section>"

    def score_bars(rows: list[dict[str, Any]], title: str, limit: int = 15) -> str:
        bars = []
        for row in rows[:limit]:
            value = row.get("market_signal_score")
            if not isinstance(value, (int, float)) or not math.isfinite(value):
                continue
            width = max(0.0, min(100.0, float(value)))
            bars.append("<div class='bar-row'>" +
                        f"<div class='bar-label mono'>{escape_html(row.get('ticker'))}</div>" +
                        f"<div class='bar-track'><div class='bar-fill' style='width:{width:.2f}%'></div></div>" +
                        f"<div class='bar-value'>{width:.1f}</div>" +
                        "</div>")
        if not bars:
            return ""
        return f"<section><h2>{escape_html(title)}</h2><div class='chart-card'>{''.join(bars)}</div></section>"

    def return_bars(rows: list[dict[str, Any]], title: str, field: str = "ret_20d", limit: int = 20) -> str:
        selected = [r for r in rows[:limit] if isinstance(r.get(field), (int, float)) and math.isfinite(float(r.get(field)))]
        if not selected:
            return ""
        max_abs = max(abs(float(r[field])) for r in selected) or 1.0
        bars = []
        for row in selected:
            value = float(row[field])
            width = max(1.0, min(100.0, abs(value) / max_abs * 100.0))
            css_class = "bar-fill positive" if value >= 0 else "bar-fill negative"
            bars.append("<div class='bar-row'>" +
                        f"<div class='bar-label mono'>{escape_html(row.get('ticker'))}</div>" +
                        f"<div class='bar-track'><div class='{css_class}' style='width:{width:.2f}%'></div></div>" +
                        f"<div class='bar-value'>{escape_html(fmt_pct(value))}</div>" +
                        "</div>")
        return f"<section><h2>{escape_html(title)}</h2><div class='chart-card'>{''.join(bars)}</div></section>"

    cards = [
        ("Latest market date", summary.get("latest_market_date")),
        ("Signals", summary.get("signals_count")),
        ("Requested tickers", summary.get("requested_tickers")),
        ("Successful tickers", summary.get("successful_tickers")),
        ("Above SMA50", fmt_pct(breadth.get("pct_above_sma50"))),
        ("Above SMA200", fmt_pct(breadth.get("pct_above_sma200"))),
        ("20d positive", fmt_pct(breadth.get("pct_positive_20d"))),
        ("Median 20d return", fmt_pct(breadth.get("median_ret_20d"))),
    ]
    card_html = "".join(f"<div class='card'><span>{escape_html(k)}</span><b>{escape_html(v)}</b></div>" for k, v in cards)
    anchors = summary.get("anchors") or []
    top_signals = summary.get("top_signals") or []
    bottom_signals = summary.get("bottom_signals") or []

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Market Signal Analysis</title>
<style>
:root {{ color-scheme: light dark; --bg:#0f172a; --panel:#111827; --panel2:#0b1220; --text:#e5e7eb; --muted:#94a3b8; --line:#334155; --accent:#60a5fa; --good:#a7f3d0; --bad:#fecaca; }}
body {{ margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; background:var(--bg); color:var(--text); }}
main {{ max-width: 1480px; margin: 0 auto; padding: 24px; }}
h1 {{ margin:0 0 4px; font-size: 28px; }}
p {{ color:var(--muted); margin: 0 0 20px; }}
.grid {{ display:grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap:12px; margin: 18px 0 24px; }}
.card, .chart-card, .explain {{ background:var(--panel); border:1px solid var(--line); border-radius:16px; padding:14px; }}
.card span {{ display:block; color:var(--muted); font-size:12px; }}
.card b {{ font-size:20px; }}
section {{ margin: 24px 0; }}
h2 {{ font-size: 18px; margin: 0 0 10px; }}
.dashboard {{ display:grid; grid-template-columns: repeat(auto-fit, minmax(360px, 1fr)); gap:16px; align-items:start; }}
.explain {{ color:var(--muted); line-height:1.45; }}
.explain b {{ color:var(--text); }}
.bar-row {{ display:grid; grid-template-columns: 118px 1fr 72px; gap:10px; align-items:center; margin: 8px 0; }}
.bar-label {{ color:var(--text); overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }}
.mono {{ font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }}
.bar-track {{ height: 12px; background:var(--panel2); border:1px solid var(--line); border-radius:999px; overflow:hidden; }}
.bar-fill {{ height:100%; background:var(--accent); border-radius:999px; }}
.bar-fill.positive {{ background:var(--good); }}
.bar-fill.negative {{ background:var(--bad); }}
.bar-value {{ color:var(--muted); font-variant-numeric: tabular-nums; text-align:right; }}
.table-wrap {{ width:100%; overflow-x:auto; border:1px solid var(--line); border-radius:14px; }}
table {{ width:100%; border-collapse: collapse; background:var(--panel); }}
th, td {{ padding: 8px 10px; border-bottom:1px solid var(--line); font-size: 13px; text-align:right; white-space: nowrap; }}
th:first-child, td:first-child, th:nth-child(2), td:nth-child(2) {{ text-align:left; }}
th {{ color:var(--muted); font-weight:600; }}
.footer {{ margin-top: 30px; color: var(--muted); font-size: 12px; }}
</style>
</head>
<body><main>
<h1>Market Signal Analysis</h1>
<p>Real market data only. Generated {escape_html(summary.get('generated_at_utc'))}. Universe: {escape_html(summary.get('universe_source'))}.</p>
<div class="grid">{card_html}</div>
<div class="dashboard">
  {breadth_chart()}
  {score_bars(anchors, 'Cross-asset anchor scores', limit=25)}
  {return_bars(anchors, 'Cross-asset 20d returns', field='ret_20d', limit=25)}
  {score_bars(top_signals, 'Strongest signal scores', limit=15)}
</div>
<section><h2>How to read this</h2><div class="explain">
<b>Market breadth</b> tells you how broad the move is across the whole fetched universe, not just the indexes. A high Above SMA50/SMA200 reading means many listed symbols are in medium/long-term uptrends. <b>20d positive</b> is the share with positive 20-trading-day returns. <b>Median 20d return</b> is the middle stock/ETF return over that window. <b>market_signal_score</b> is a 0-100 composite ranking of momentum, trend, volatility, drawdown, and high/low proximity. Labels map to score bands: strong, constructive, neutral, weak, stressed.</div></section>
{rows_table(anchors, 'Cross-asset anchors')}
{rows_table(top_signals, 'Top market signals')}
{rows_table(bottom_signals, 'Weakest market signals')}
<div class="footer">Outputs: data/signals_latest.csv, data/quotes_long.csv, data/market_summary.json, data/fetch_manifest.json.</div>
</main></body></html>
"""
    path.write_text(html, encoding="utf-8")

def save_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=False), encoding="utf-8")


def fetch_all_quotes(tickers: list[str], args: argparse.Namespace) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    all_rows: list[dict[str, Any]] = []
    failures: list[dict[str, str]] = []
    log(f"[INFO] Fetching real quote history for {len(tickers)} tickers using sources={','.join(args.sources)}")
    log(f"[INFO] First 30 tickers: {', '.join(tickers[:30])}")
    done = 0
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        future_map = {pool.submit(fetch_symbol, ticker, args): ticker for ticker in tickers}
        for future in as_completed(future_map):
            ticker = future_map[future]
            done += 1
            try:
                result = future.result()
            except Exception as exc:
                result = FetchResult(ticker, [], None, str(exc))
            if result.rows:
                all_rows.extend(result.rows)
            else:
                failures.append({"ticker": ticker, "error": result.error or "no rows"})
            if done % args.progress_every == 0 or done == len(tickers):
                ok = done - len(failures)
                log(f"[INFO] Progress {done}/{len(tickers)}; ok={ok}; failed={len(failures)}")
    return all_rows, failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Fetch real market data and build market signal analysis outputs.")
    parser.add_argument("--universe", choices=["us-all", "seed", "anchors", "custom"], default=os.getenv("MARKET_UNIVERSE", "us-all"))
    parser.add_argument("--tickers-file", default=os.getenv("MARKET_TICKERS_FILE", "data/tickers.csv"))
    parser.add_argument("--output-dir", default=os.getenv("MARKET_OUTPUT_DIR", "docs/data"))
    parser.add_argument("--html", default=os.getenv("MARKET_HTML", "docs/index.html"))
    parser.add_argument("--period", default=os.getenv("MARKET_PERIOD", "1y"), help="Yahoo chart range, e.g. 6mo, 1y, 2y, 5y")
    parser.add_argument("--interval", default=os.getenv("MARKET_INTERVAL", "1d"), help="Yahoo chart interval, e.g. 1d")
    parser.add_argument("--sources", default=os.getenv("MARKET_SOURCES", "yahoo,stooq"), help="Comma list: yahoo,stooq")
    parser.add_argument("--workers", type=int, default=int(os.getenv("MARKET_WORKERS", "12")))
    parser.add_argument("--retries", type=int, default=int(os.getenv("MARKET_RETRIES", "2")))
    parser.add_argument("--timeout", type=int, default=int(os.getenv("MARKET_TIMEOUT", "30")))
    parser.add_argument("--max-tickers", type=int, default=int(os.getenv("MARKET_MAX_TICKERS", "0")), help="0 means no cap")
    parser.add_argument("--min-history-days", type=int, default=int(os.getenv("MARKET_MIN_HISTORY_DAYS", "60")))
    parser.add_argument("--progress-every", type=int, default=int(os.getenv("MARKET_PROGRESS_EVERY", "100")))
    parser.add_argument("--include-special", action="store_true", help="include warrants, units, rights, preferreds from listing files")
    parser.add_argument("--strict-universe", action="store_true", help="fail if live universe files cannot be read")
    args = parser.parse_args(argv)
    args.sources = [s.strip().lower() for s in str(args.sources).split(",") if s.strip()]

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    tickers, universe_source, source_note = resolve_universe(args)
    if not tickers:
        log("[ERROR] Universe resolved to zero tickers.")
        return 2
    if source_note:
        log(f"[WARN] {source_note}")

    write_csv(out_dir / "universe.csv", [{"ticker": t} for t in tickers], ["ticker"])
    all_rows, failures = fetch_all_quotes(tickers, args)
    if not all_rows:
        log("[ERROR] No real market quote rows were fetched. Refusing to create simulated/fake outputs.")
        save_json(out_dir / "fetch_manifest.json", {
            "generated_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
            "universe_source": universe_source,
            "requested_tickers": len(tickers),
            "successful_tickers": 0,
            "failed_tickers": len(failures),
            "failures": failures[:500],
        })
        return 3

    all_rows.sort(key=lambda r: (r.get("ticker") or "", r.get("date") or ""))
    quote_fields = ["date", "ticker", "open", "high", "low", "close", "adj_close", "volume", "source"]
    write_csv(out_dir / "quotes_long.csv", all_rows, quote_fields)

    signals = compute_latest_signals(all_rows, args.min_history_days)
    if not signals:
        log("[ERROR] Quotes were fetched, but no ticker had enough real history for signal analysis.")
        return 4

    signal_fields = [
        "ticker", "last_date", "last_close", "rows", "source", "signal_label", "market_signal_score",
        "ret_1d", "ret_5d", "ret_20d", "ret_63d", "ret_126d", "ret_252d",
        "sma20", "sma50", "sma200", "above_sma20", "above_sma50", "above_sma200",
        "distance_sma50", "distance_sma200", "realized_vol_20d", "rsi14", "drawdown_252d",
        "near_20d_high", "near_20d_low", "distance_52w_high", "distance_52w_low", "avg_volume_20d",
        "rank_ret_5d", "rank_ret_20d", "rank_ret_63d", "rank_ret_126d", "rank_low_vol_20d", "rank_drawdown_252d",
    ]
    write_csv(out_dir / "signals_latest.csv", signals, signal_fields)

    successful = len({row["ticker"] for row in all_rows})
    manifest = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
        "universe_source": universe_source,
        "universe_note": source_note,
        "requested_tickers": len(tickers),
        "successful_tickers": successful,
        "failed_tickers": len(failures),
        "quote_rows": len(all_rows),
        "signals_count": len(signals),
        "period": args.period,
        "interval": args.interval,
        "sources": args.sources,
        "failures": failures[:1000],
    }
    save_json(out_dir / "fetch_manifest.json", manifest)
    summary = build_summary(signals, manifest)
    save_json(out_dir / "market_summary.json", summary)
    if args.html:
        write_html_report(Path(args.html), summary)

    log(f"[INFO] Completed. requested={len(tickers)} successful={successful} failed={len(failures)} signals={len(signals)}")
    log(f"[INFO] Wrote {out_dir / 'signals_latest.csv'} and {out_dir / 'market_summary.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
